feat(): add implemented API feature list
evoila/osb-docs pull request #5
Opened 2019-09-13 08:41 UTC by joStrauss

This list is based upon the git history of the framework and changelog of the osb-api

2019-09-13 09:44 UTC, chbrinker requested changes

2019-09-13 09:44 UTC, chbrinker commented on pages/osb-api-features.md
> +- Asynchronous Bindings: Bindings can be performed async, and a polling endpoint has been added.
async --> asynchronously

2019-09-13 09:44 UTC, chbrinker commented on pages/osb-api-features.md
> +- Asynchronous Bindings: Bindings can be performed async, and a polling endpoint has been added.
Either and or make two sentences. Remove the commata

2019-09-13 09:44 UTC, chbrinker commented on pages/osb-api-features.md
> +- Request Identity: A Platform might wish to uniquely identify a specific request as it flows throughout the system. For example, this might be used for logging for request tracing purposes.
Platform -> platform

2019-09-13 09:44 UTC, chbrinker commented on pages/osb-api-features.md
> +- Request Identity: A Platform might wish to uniquely identify a specific request as it flows throughout the system. For example, this might be used for logging for request tracing purposes.
" as it flows throughout the system" sounds odd

2019-09-13 09:44 UTC, chbrinker commented on pages/osb-api-features.md
> +- Request Identity: A Platform might wish to uniquely identify a specific request as it flows throughout the system. For example, this might be used for logging for request tracing purposes.
"for logging for request " thats no correct English. And I am even not sure what you want to explain here.

2019-09-16 09:14 UTC, marberger requested changes
The osb-api-features site is missing the formal parts like the table of contents and footer links. 

Furthermore no links to the new page have been added to any other page (table of contents) and no footer links to the previous and next page for already existing pages.

2019-09-16 09:14 UTC, marberger commented on pages/osb-api-features.md
> +This Documents sums up all OSB-API features, that got added after v2.12, the frameworks implements so far. The framework supports all API features up to version 2.14 and is currently upgraded to supp
"is currently **being** upgraded to support"

2019-09-16 09:14 UTC, marberger commented on pages/osb-api-features.md
> +- Asynchronous Bindings: Bindings can be performed aynchronous and a polling endpoint has been added.
"aynchronous" -> missing "s"
Don't you use an adverb at this point? -> asynchronously

2019-09-16 09:14 UTC, marberger commented on pages/osb-api-features.md
> +
Missing Table of Contents with Links.

2019-09-16 09:14 UTC, marberger commented on pages/osb-api-features.md
> +- Maintenance Info: The service catalogs now holds an object to specify consequences of an provision or update action. This gives the user information about the steps initiated by the service broker
Missing footer with link to next and previous page.

2019-09-23 09:23 UTC, marberger requested changes

2019-09-23 09:23 UTC, marberger commented on pages/ide-runtime.md
> +7. [Open Service Broker API Features](osb-features.md)
6. Development is missing

2019-09-23 09:23 UTC, marberger commented on pages/license.md
>  8. [Contribution](contribution.md)
No 9th item

2019-09-23 09:23 UTC, marberger commented on pages/osb-api-features.md
> +    * [7.1 Open Service Broker API v2.13](#open-service-broker-api-v2.13)
Three times 7.1

2019-09-23 09:32 UTC, marberger approved these changes

2019-09-24 08:47 UTC, merged